name = "fastgraph"
type = "javascript"

account_id = "771c00eaa86cd480f93dc6f41b51398f"
route = "https://api-test.lemune.com/graphql/"
zone_id = "cb3bb6975444b93de2d7bbf0e31902c8"
target_type = "javascript"
usage_model= "bundled"
kv_namespaces = [
         { binding = "APQ_CACHE", id = "b55e3bd6a8bc4298b443b219a59469e6", preview_id=  "b55e3bd6a8bc4298b443b219a59469e6"},
         { binding = "SCHEMA", id = "673daed11f53492fb2cc24732c1b11ef", preview_id = "673daed11f53492fb2cc24732c1b11ef" }
]

[vars]
ORIGIN_URL = "https://api-test-original.lemune.com/graphql/"
SCOPE = "AUTHENTICATED"
IGNORE_ORIGIN_CACHE_HEADERS = "1"
DEFAULT_TTL = "900"
SWR = "30"
PRIVATE_TYPES = ""
GENERIC_TYPES = ""
AUTH_DIRECTIVE = ""
APQ_TTL = "30"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"
