name = "fastgraph"
type = "javascript"

account_id = "1a2a1312f9b14c0611a47d3a511472f7"
workers_dev = true
route = "fastgraph.fastgraph.de/*"
zone_id = ""
target_type = "javascript"
usage_model= "unbound"
kv_namespaces = [ 
         { binding = "QUERY_CACHE", id = "7a9f62c214174394b4e3974acc949d07", preview_id = "7a9f62c214174394b4e3974acc949d07" },
         { binding = "APQ_CACHE", id = "9c2e58947cad40a0ac8f0f3340181887", preview_id = "9c2e58947cad40a0ac8f0f3340181887" }
]

[vars]
ORIGIN_URL = "https://gitlab.com/api/graphql"
SCOPE = "PUBLIC"
IGNORE_ORIGIN_CACHE_HEADERS = "1"
DEFAULT_TTL = "900"
SWR = "900"
PRIVATE_TYPES = ""
AUTH_DIRECTIVE = "auth"
APQ_TTL = "900"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"