name = "graphcdn"
type = "javascript"

account_id = "1a2a1312f9b14c0611a47d3a511472f7"
workers_dev = true
route = "graphcdn.microhug.com/*"
zone_id = ""
target_type = "javascript"
usage_model= "unbound"
kv_namespaces = [ 
         { binding = "QUERY_CACHE", id = "4b5096c559034695be4d83fa91540c2c", preview_id = "4b5096c559034695be4d83fa91540c2c" },
         { binding = "APQ_CACHE", id = "82297ebf17a64833a33b865703e40fca", preview_id = "82297ebf17a64833a33b865703e40fca" }
]

[vars]
ORIGIN_URL = "https://countries.trevorblades.com/"
SCOPE = "PUBLIC"
IGNORE_ORIGIN_CACHE_HEADERS = "1"
DEFAULT_TTL = "900"
SWR = "900"
PRIVATE_TYPES = ""
AUTH_DIRECTIVE = "auth"
INJECT_ORIGIN_HEADERS = ""
APQ_TTL = "900"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"