name = "graphcdn"
type = "javascript"

account_id = "1a2a1312f9b14c0611a47d3a511472f7"
workers_dev = true
route = "graphcdn.microhug.com/"
zone_id = ""
target_type = "javascript"
usage_model= "unbound"
kv_namespaces = [ 
         { binding = "QUERY_CACHE", id = "4b5096c559034695be4d83fa91540c2c", preview_id = "4b5096c559034695be4d83fa91540c2c" },
         { binding = "GRAPHQL_SCHEMA", id = "deb5af2721a148f7a25d04c49ac36eb3", preview_id = "deb5af2721a148f7a25d04c49ac36eb3" }
]

[vars]
ORIGIN_URL = "https://gitlab.com/api/graphql"
INTROSPECTION_URL = "https://gitlab.com/api/graphql"
SCOPE = "PUBLIC"
IGNORE_ORIGIN_CACHE_HEADERS = "0"
DEFAULT_TTL = "900"
PRIVATE_TYPES = ""
AUTH_DIRECTIVE = ""
INJECT_ORIGIN_HEADERS = ""

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"

[triggers]
crons = ["*/30 * * * *"]