name = "fastgraph"
type = "javascript"

account_id = "1a2a1312f9b14c0611a47d3a511472f7"
route = "https://gitlab.fastgraph.de"
zone_id = "9cafb7ea2380c99f3b955baccc064027"
target_type = "javascript"
usage_model= "unbound"
kv_namespaces = [ 
         { binding = "QUERY_CACHE", id = "7a9f62c214174394b4e3974acc949d07", preview_id = "7a9f62c214174394b4e3974acc949d07" },
         { binding = "APQ_CACHE", id = "9c2e58947cad40a0ac8f0f3340181887", preview_id = "9c2e58947cad40a0ac8f0f3340181887" },
         { binding = "SCHEMA", id = "3778588748ff4f9dab10291b3baccaba", preview_id = "3778588748ff4f9dab10291b3baccaba" }
]

[vars]
ORIGIN_URL = "https://gitlab.com/api/graphql"
SCOPE = "PUBLIC"
IGNORE_ORIGIN_CACHE_HEADERS = "1"
DEFAULT_TTL = "900"
SWR = "30"
PRIVATE_TYPES = ""
AUTH_DIRECTIVE = ""
APQ_TTL = "30"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"