name = "fastgraph"
type = "javascript"

account_id = "771c00eaa86cd480f93dc6f41b51398f"
route = "https://api-test-original.lemune.com/graphql/"
zone_id = "cb3bb6975444b93de2d7bbf0e31902c8"
target_type = "javascript"
usage_model= "bundled"
kv_namespaces = [
         { binding = "lemune-stg", id = "c2a12580f1fb4c38a414bf785918d5e2", preview_id = "c2a12580f1fb4c38a414bf785918d5e2" },
         { binding = "lemune-stg-schema", id = "df933d5df2af49069ab21274bcac0d2c", preview_id = "df933d5df2af49069ab21274bcac0d2c" }
]

[vars]
ORIGIN_URL = "https://api-test-original.lemune.com/graphql/"
SCOPE = "PUBLIC"
IGNORE_ORIGIN_CACHE_HEADERS = "1"
DEFAULT_TTL = "900"
SWR = "30"
PRIVATE_TYPES = "App, User, Group, Order, Stock, Address, Channel, Invoice, Payment, Webhook, AppToken, Checkout, GiftCard, OrderLine, Warehouse, OrderEvent, ExportEvent, Fulfillment, Transaction, AppExtension, CheckoutLine, PreorderData, GiftCardEvent, OrderDiscount, PaymentSource, DigitalContent, UserPermission, SaleChannelListing, ProductChannelListing, VoucherChannelListing, SaleTranslatableContent, CollectionChannelListing, VoucherTranslatableContent, ProductVariantChannelListing, ShippingMethodTranslatableContent, userOrders, accountAddresses"
AUTH_DIRECTIVE = ""
APQ_TTL = "30"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"
