name: Deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason for the release'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Compiles
        run: npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
